### ISSUE TITLE
 Pi-Gro won't start after update

### ISSUE THREAD

**Issue by Rak1ta** [actionschnitzel/PiGro-Aid-#70]
Error on startup.
```
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```

```
pi@raspberrypi:~ $ /home/pi/PiGro-Aid-/start.sh
[Info]: Hi,pi waz uuuuup?!
[Info]: /home/pi is your home directory!
[Info]: PiGro directory is /home/pi
[Info]: Folder: .pigro exsists
[Info]: pigro.conf exsists
[Info]: Your Distro is: raspbian
[Info]: Your DE is: LXDE
[Info]: Pi-Apps is installed list will be added
[Info]: Snap is installed
[Info]: Flatpak is installed
[Info]: 9 Flatpaks are installed
[Info]: pigro.conf exists
[Info]: 4043 .deb Packages Installed
[Info]: Dark Theme
Traceback (most recent call last):
  File "/home/pi/PiGro-Aid-/src/pigro_main.py", line 7368, in <module>
    app = MainApplication()
  File "/home/pi/PiGro-Aid-/src/pigro_main.py", line 49, in __init__
    file=f"{Application_path}/images/icons/logo.png")
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/home/pi/images/icons/logo.png": no such file or directory
```

**Comment by actionschnitzel** [comment]
That is strange: 
_tkinter.TclError: couldn't open "/home/pi/images/icons/logo.png": no such file or directory

The variable that determines the "Path/to/Pigrro-Aid" is crashed. 

I tried to reproduce the error. It looks like Github has destroyed everything at the Merge -.-. There are files that are no longer available in my local version. I try to upload a clean version as soon as possible

**Comment by Rak1ta** [comment]
@actionschnitzel Will you update the .deb version? Thanks!

**Comment by actionschnitzel** [comment]
I tried again this morning to clone from the main branch and everything worked properly. Looks as if Git or Github had a kind of hiccup. Very strange.

**Comment by Rak1ta** [comment]
@actionschnitzel 
tried to install now with `wget -qO- https://raw.githubusercontent.com/actionschnitzel/PiGro-Aid-/installer/install.sh |bash` - running
version 23.02 from pi-apps - does not start
version 23.01 from pi-apps - running

**Comment by actionschnitzel** [comment]
I don't get it. I deleted the release 3 times end every time is says 2 weeks ago 

![Bildschirmfoto vom 2023-04-07 10-17-06](https://user-images.githubusercontent.com/67635013/230571200-d86ac6d1-36b2-4d6e-bbc8-2e8068905dd4.png)

**Comment by Rak1ta** [comment]
@actionschnitzel Something went wrong while creating the new version. Your release has been [saved with changes](https://github.com/actionschnitzel/PiGro-Aid-/tree/23.02) for two weeks ago.

**Comment by actionschnitzel** [comment]
I made a few changes and deleted the tag 23.02 which is bind to the version from 2 week ago. Also I updated the .deb files on github and the repo. Tested and worked.
Sorry for the inconvenience
![Bildschirmfoto vom 2023-04-07 11-46-18](https://user-images.githubusercontent.com/67635013/230587294-53503f9f-ad07-49c0-931a-ee2086f7c4e4.png)

**Comment by Rak1ta** [comment]
@actionschnitzel It all works, thank you.
