### ISSUE TITLE
Ethernet IP address not shown when using NetworkManager

### ISSUE THREAD

**Issue by Botspot** [actionschnitzel/PiGro-Aid-#76]
This may already be fixed in PiGro 24, but I just wanted to mention that in PiOS Bullseye, if you use `raspi-config` to switch to NetworkManager, no IP address is displayed on the PiGro dashboard.

**Comment by actionschnitzel** [comment]
That's good to know. This problem must be new. Before switching to `Bookworm` I used `Bullseye` with` XFCE` and used `NetworkManger` to use Wi-FI. For 24.01 ***Network*** on the ***Dashbord_TAB*** was completely rewritten. I will check this carefully.

***ADDED TO:*** https://github.com/actionschnitzel/PiGro-Aid-/issues/74 Network | Check if IP is displayed with NetworkManager

**Comment by actionschnitzel** [comment]
> This may already be fixed in PiGro 24, but I just wanted to mention that in PiOS Bullseye, if you use `raspi-config` to switch to NetworkManager, no IP address is displayed on the PiGro dashboard.

Tested this on up to date PiOS Legacy64 /Pi400. v24.01 no longer has this problem.
