### ISSUE TITLE
Widevine info outdated

### ISSUE THREAD

**Issue by Botspot** [actionschnitzel/PiGro-Aid-#78]
I'm pretty sure 64-bit Bullseye and Bookworm have had a 64-bit compatible version of `libwidevinecdm0` out for a while now. (citation needed)
Your Tuning tab still says that the 32-bit Chromium is necessary for DRM support, which has been true, but it no longer is.

Please do not take my word for it; I avoid using DRM but this is my current understanding of the situation: that widevine now works for 64-bit Chromium.

**Comment by actionschnitzel** [comment]
Widevide now works normally on PiOS arm64. 
The function was already removed for version 24.01.

https://github.com/actionschnitzel/PiGro-Aid-/issues/74 Tuning:

-  Remove Chromium32 installer
