### ISSUE TITLE
PiGro startet nicht

### ISSUE THREAD

**Issue by chietal** [actionschnitzel/PiGro-Aid-#82]
Guten Abend,

ich bekomme PiGro auf Raspberry OS / Bookworm einfach nicht gestartet. Wenn ich es über den Desktop Link starte, passiert gar nichts. Wenn ich es im Terminal ausführe, bekomme ich folgende Meldung:

[Info] You are using PiGro 24.01
[Info] /home/pi/.config/autostart/ already exists
[Info] 2438 .deb Packages Installed
[Info] Snap is installed, and there are 12 packages installed.
[Info] Flatpak is installed. List will be added
Added Flatpak cache.
[Info] Pi-Apps is installed. List will be added
[Info] Raspberry Pi Model: Raspberry Pi 4 Model B Rev 1.5
Traceback (most recent call last):
  File "/opt/PiGro-JCI/src/main.py", line 273, in <module>
    app = MainApplication()
          ^^^^^^^^^^^^^^^^^
  File "/opt/PiGro-JCI/src/main.py", line 146, in __init__
    self.dash_tab = DashTab(self.notebook)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PiGro-JCI/src/tabs/dash_tab.py", line 461, in __init__
    self.update_labels()
  File "/opt/PiGro-JCI/src/tabs/dash_tab.py", line 556, in update_labels
    f"{get_window_manager_name()}",
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PiGro-JCI/src/tabs/dash_tab.py", line 535, in get_window_manager_name
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wmctrl'

Ich habe es überprüft, wmctrl ist installiert. Wieso kann der Pfad nicht gefunden werden?
Wie kann ich das beheben?
Vielen Dank im Voraus!

**Comment by actionschnitzel** [comment]
Hallo,

ich kann den Fehler leider nicht reproduzieren. Ich habe das Ganze auf einem frischen PiOS überprüft, und 'wmctrl -m' wird anstandslos ausgeführt. Hast du eventuell Modifikationen an deinem System vorgenommen oder es längere Zeit nicht aktualisiert?

#P.S .. Der User Name "Pi" ist nicht unbedingt sich!

**Comment by chietal** [comment]
Hallo,

Danke für deine Rückmeldung.
Das System ist recht frisch und immer auf dem neuesten Stand. Ich verwende ihn täglich als Multimedia Player und mache immer dann Updates, wenn welche verfügbar sind. 

PiGro wurde auch als erstes mit installiert und funktionierte von Anfang an nicht.
Noch zur Info, ich verwende die 32bit Version von PiOS, macht das ggf etwas aus?

**Comment by chietal** [comment]
Ich danke dir, probiere ich aus!
Ich bin noch auf 32bit, weil ich Game Emulatoren nutze und viele nur dort unterstützt werden. Mit 64bit habe ich da viele Probleme. Doch nun weiß ich woran es liegt. :-)

**Comment by actionschnitzel** [comment]
Das freut mich! Ich hab allerdings viel zu kompliziert gedacht. Es wäre für uns beide viel einfacher gewesen, wenn ich dir PiGro mit der Änderung neu gepackt hätte. Also falls du es nochmal brauchen solltest:
[PiGro_24_01_armhf.tar.gz](https://github.com/actionschnitzel/PiGro-Aid-/files/13987863/PiGro_24_01_armhf.tar.gz)

**Comment by chietal** [comment]
Ich danke dir für alles, das macht einen wahren Programmierer aus!
Ich wusste wie es geht und habe alles erledigt bekommen, also kein Problem! 
Diese version habe ich mir gleich heruntergeladen und abgespeichert!

Danke für deine wundervolle Zuarbeit!
