### ISSUE TITLE
Pigro fails to start on Raspberry Pi 5 using "x" instead of wayland.

### ISSUE THREAD

**Issue by CTinMich** [actionschnitzel/PiGro-Aid-#84]
There is a bug in the Raspberry Pi 5 config that prevents "RealVnc" from starting (uses a Wayland based VNC?) unless you switch from Wayland to "X".  When I did that, it made something incompatible with the PiGro config.  Gui start does nothing and from the command line I see this error:

pi@MyPi5-01:~ $ pigro-jci
[Info] You are using PiGro 24.02
[Info] /home/pi/.config/autostart/ already exists
Traceback (most recent call last):
  File "/opt/PiGro-JCI/src/main.py", line 7, in <module>
    from resorcess import *
  File "/opt/PiGro-JCI/src/resorcess.py", line 179, in <module>
    theme = get_theme().lower()
            ^^^^^^^^^^^
  File "/opt/PiGro-JCI/src/resorcess.py", line 158, in get_theme
    theme = get_lxde_theme_name()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PiGro-JCI/src/resorcess.py", line 124, in get_lxde_theme_name
    with open(config_file_path, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.config/lxsession/LXDE-pi/desktop.conf'

**Comment by actionschnitzel** [comment]
Hi, I managed to reproduce the error. It seems that ~/.config/lxsession/LXDE-pi/desktop.conf in Bookworm is not created automatically (as it was before Wayland). There is a simple workaround:

Please go to the Panel Menu and open `Appearance Settings`. The path and the necessary config file should be created then.
Hope that helps. A hotfix will follow in a few days.

**Comment by CTinMich** [comment]
Yes... the steps you listed fixed the PiGro launch :)  Thanks!!!
