### ISSUE TITLE
Remove PiKISS from PiGro

### ISSUE THREAD

**Issue by Botspot** [actionschnitzel/PiGro-Aid-#87]
We at Pi-Apps today finally had to stop offering PiKISS due to a history of it being poorly maintained and the combative behavior from the developer.
See: https://github.com/jmcerrejon/PiKISS/issues/209#issuecomment-2024386234

PiGro currently has a one-click for installing PiGro from Pi-Apps, which will no longer work.
You could either add pikiss integration into PiGro yourself, or just remove it as we have done. It's up to you, but I thought it would be nice to let you know of the change before somebody complains that the piKiss install button stopped working.

**Comment by actionschnitzel** [comment]
Wow...
Thank you for letting me know. I will completely remove it. I've been thinking about removing PiKiss anyway for some time now. :-(
